const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

// Load models
const User = require('./models/User');
const Company = require('./models/Company');
const Job = require('./models/Job');

require('dotenv').config();
const MONGO_URI = process.env.MONGO_URI || process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/jobportal';

async function seed() {
    await mongoose.connect(MONGO_URI);
    console.log('✅ Connected to MongoDB');

    // ─────────────────────────────────────────────
    // 1. Create a Recruiter User (seed owner)
    // ─────────────────────────────────────────────
    let recruiter = await User.findOne({ email: 'seedrecruiter@jobportal.com' });
    if (!recruiter) {
        const hashed = await bcrypt.hash('Seed@1234', 10);
        recruiter = await User.create({
            firstName: 'Seed',
            lastName: 'Recruiter',
            email: 'seedrecruiter@jobportal.com',
            password: hashed,
            role: 'recruiter',
            isVerified: true,
        });
        console.log('✅ Created recruiter user');
    } else {
        console.log('ℹ️  Recruiter user already exists');
    }

    // ─────────────────────────────────────────────
    // 2. Create 10 Companies
    // ─────────────────────────────────────────────
    const companiesData = [
        {
            name: 'Tata Consultancy Services',
            about: 'TCS is a global IT services, consulting and business solutions organization with 600,000+ associates.',
            companyType: 'MNC',
            industries: ['AI/ML', 'Web/SaaS'],
            size: '10000+',
            location: 'Mumbai, Maharashtra',
            website: 'https://www.tcs.com',
            officialEmail: 'careers@tcs.com',
        },
        {
            name: 'Infosys Limited',
            about: 'Infosys is a global leader in next-generation digital services and consulting, enabling clients in over 50 countries.',
            companyType: 'MNC',
            industries: ['Web/SaaS', 'FinTech'],
            size: '10000+',
            location: 'Bengaluru, Karnataka',
            website: 'https://www.infosys.com',
            officialEmail: 'hr@infosys.com',
        },
        {
            name: 'Wipro Technologies',
            about: 'Wipro is a leading global IT, consulting, and business process services company.',
            companyType: 'MNC',
            industries: ['AI/ML', 'IoT'],
            size: '10000+',
            location: 'Bengaluru, Karnataka',
            website: 'https://www.wipro.com',
            officialEmail: 'talent@wipro.com',
        },
        {
            name: 'Razorpay',
            about: 'Razorpay is India\'s leading full-stack financial solutions company, powering payments for 8 million+ businesses.',
            companyType: 'Unicorn Startup',
            industries: ['FinTech'],
            size: '501-1000',
            location: 'Bengaluru, Karnataka',
            website: 'https://www.razorpay.com',
            officialEmail: 'jobs@razorpay.com',
        },
        {
            name: 'BYJU\'S EdTech',
            about: 'BYJU\'S is the world\'s most valuable EdTech company transforming learning for 150M+ students globally.',
            companyType: 'Unicorn Startup',
            industries: ['EdTech'],
            size: '10000+',
            location: 'Bengaluru, Karnataka',
            website: 'https://www.byjus.com',
            officialEmail: 'careers@byjus.com',
        },
        {
            name: 'Apollo Hospitals',
            about: 'Apollo Hospitals Group is one of Asia\'s largest healthcare groups with 72 hospitals across India.',
            companyType: 'Enterprise',
            industries: ['Healthcare', 'Hospital'],
            size: '10000+',
            location: 'Chennai, Tamil Nadu',
            website: 'https://www.apollohospitals.com',
            officialEmail: 'hr@apollohospitals.com',
        },
        {
            name: 'Flipkart Internet',
            about: 'Flipkart is India\'s leading e-commerce marketplace with 400M+ registered users and 150M+ products.',
            companyType: 'MNC',
            industries: ['E-commerce', 'AI/ML'],
            size: '10000+',
            location: 'Bengaluru, Karnataka',
            website: 'https://www.flipkart.com',
            officialEmail: 'careers@flipkart.com',
        },
        {
            name: 'Zomato Ltd',
            about: 'Zomato is India\'s leading food delivery and restaurant discovery platform operating in 500+ cities.',
            companyType: 'Unicorn Startup',
            industries: ['E-commerce'],
            size: '10000+',
            location: 'Gurugram, Haryana',
            website: 'https://www.zomato.com',
            officialEmail: 'talent@zomato.com',
        },
        {
            name: 'HDFC Bank',
            about: 'HDFC Bank is India\'s largest private sector bank offering a wide range of banking and financial services.',
            companyType: 'Enterprise',
            industries: ['FinTech'],
            size: '10000+',
            location: 'Mumbai, Maharashtra',
            website: 'https://www.hdfcbank.com',
            officialEmail: 'careers@hdfcbank.com',
        },
        {
            name: 'Mahindra & Mahindra',
            about: 'Mahindra is a $21 billion multinational group operating in key industries across 100+ countries.',
            companyType: 'MNC',
            industries: ['Manufacturing', 'IoT'],
            size: '10000+',
            location: 'Mumbai, Maharashtra',
            website: 'https://www.mahindra.com',
            officialEmail: 'hr@mahindra.com',
        },
    ];

    const companies = [];
    for (const data of companiesData) {
        let co = await Company.findOne({ name: data.name });
        if (!co) {
            co = await Company.create({ ...data, createdBy: recruiter._id, verified: true, verificationStatus: 'verified' });
            console.log(`✅ Created company: ${data.name}`);
        } else {
            console.log(`ℹ️  Company exists: ${data.name}`);
        }
        companies.push(co);
    }

    // ─────────────────────────────────────────────
    // 3. Create 50 Jobs across all categories
    // ─────────────────────────────────────────────
    const jobsData = [
        // ── IT (6 jobs) ──
        {
            title: 'Senior React Developer',
            company: companies[0], location: 'Mumbai, Maharashtra',
            type: 'Full Time', category: 'IT',
            salary: '₹18,00,000 - ₹25,00,000 / Year',
            minSalary: 1800000, maxSalary: 2500000,
            experienceLevel: 'Senior Level',
            tags: ['React', 'JavaScript', 'Redux', 'Node.js'],
            requiredSkills: ['React.js', 'JavaScript', 'Redux', 'REST APIs'],
            description: 'We are looking for a Senior React Developer to build scalable web applications for our enterprise clients globally.',
        },
        {
            title: 'Full Stack Java Developer',
            company: companies[1], location: 'Bengaluru, Karnataka',
            type: 'Full Time', category: 'IT',
            salary: '₹14,00,000 - ₹20,00,000 / Year',
            minSalary: 1400000, maxSalary: 2000000,
            experienceLevel: 'Mid-Senior Level',
            tags: ['Java', 'Spring Boot', 'React', 'MySQL'],
            requiredSkills: ['Java', 'Spring Boot', 'Hibernate', 'MySQL'],
            description: 'Build full-stack enterprise applications using Java and modern frontend frameworks.',
        },
        {
            title: 'Python Backend Engineer',
            company: companies[2], location: 'Bengaluru, Karnataka',
            type: 'Hybrid', category: 'IT',
            salary: '₹12,00,000 - ₹18,00,000 / Year',
            minSalary: 1200000, maxSalary: 1800000,
            experienceLevel: 'Mid-Senior Level',
            tags: ['Python', 'Django', 'PostgreSQL', 'Docker'],
            requiredSkills: ['Python', 'Django', 'REST APIs', 'PostgreSQL'],
            description: 'Design and implement scalable backend services and APIs for our cloud platform.',
        },
        {
            title: 'iOS Mobile Developer',
            company: companies[6], location: 'Bengaluru, Karnataka',
            type: 'Full Time', category: 'IT',
            salary: '₹16,00,000 - ₹22,00,000 / Year',
            minSalary: 1600000, maxSalary: 2200000,
            experienceLevel: 'Senior Level',
            tags: ['Swift', 'iOS', 'Xcode', 'UIKit'],
            requiredSkills: ['Swift', 'Objective-C', 'iOS SDK', 'Xcode'],
            description: 'Develop and maintain iOS applications for millions of users on the Flipkart platform.',
        },
        {
            title: 'Android Developer',
            company: companies[7], location: 'Gurugram, Haryana',
            type: 'Full Time', category: 'IT',
            salary: '₹12,00,000 - ₹18,00,000 / Year',
            minSalary: 1200000, maxSalary: 1800000,
            experienceLevel: 'Mid-Senior Level',
            tags: ['Kotlin', 'Android', 'Jetpack', 'MVVM'],
            requiredSkills: ['Kotlin', 'Android SDK', 'Jetpack Compose', 'MVVM'],
            description: 'Build feature-rich Android apps for the Zomato food delivery platform.',
        },
        {
            title: 'Frontend Developer (Angular)',
            company: companies[0], location: 'Remote',
            type: 'Remote', category: 'IT',
            salary: '₹8,00,000 - ₹14,00,000 / Year',
            minSalary: 800000, maxSalary: 1400000,
            experienceLevel: 'Entry Level',
            tags: ['Angular', 'TypeScript', 'HTML', 'CSS'],
            requiredSkills: ['Angular', 'TypeScript', 'HTML5', 'CSS3'],
            description: 'Work as a frontend developer building enterprise dashboards for Fortune 500 clients.',
        },
        // ── Software Engineering (5 jobs) ──
        {
            title: 'Software Engineer - Cloud',
            company: companies[2], location: 'Bengaluru, Karnataka',
            type: 'Full Time', category: 'Software Engineering',
            salary: '₹15,00,000 - ₹22,00,000 / Year',
            minSalary: 1500000, maxSalary: 2200000,
            experienceLevel: 'Mid-Senior Level',
            tags: ['AWS', 'GCP', 'Kubernetes', 'Terraform'],
            requiredSkills: ['AWS', 'Cloud Architecture', 'Kubernetes', 'CI/CD'],
            description: 'Design and manage cloud infrastructure solutions for enterprise clients worldwide.',
        },
        {
            title: 'Backend Software Engineer',
            company: companies[3], location: 'Bengaluru, Karnataka',
            type: 'Full Time', category: 'Software Engineering',
            salary: '₹20,00,000 - ₹30,00,000 / Year',
            minSalary: 2000000, maxSalary: 3000000,
            experienceLevel: 'Senior Level',
            tags: ['Java', 'Microservices', 'Kafka', 'Redis'],
            requiredSkills: ['Java', 'Microservices', 'Kafka', 'Redis', 'PostgreSQL'],
            description: 'Build the core payment processing engine handling millions of transactions/day.',
        },
        {
            title: 'Software Development Engineer II',
            company: companies[6], location: 'Bengaluru, Karnataka',
            type: 'Full Time', category: 'Software Engineering',
            salary: '₹25,00,000 - ₹40,00,000 / Year',
            minSalary: 2500000, maxSalary: 4000000,
            experienceLevel: 'Senior Level',
            tags: ['System Design', 'Java', 'Distributed Systems'],
            requiredSkills: ['System Design', 'Java', 'Distributed Systems', 'Microservices'],
            description: 'Lead design and development of scalable systems powering Flipkart\'s supply chain.',
        },
        {
            title: 'Junior Software Engineer',
            company: companies[1], location: 'Pune, Maharashtra',
            type: 'Full Time', category: 'Software Engineering',
            salary: '₹5,00,000 - ₹8,00,000 / Year',
            minSalary: 500000, maxSalary: 800000,
            experienceLevel: 'Entry Level',
            tags: ['Java', 'SQL', 'Git', 'Problem Solving'],
            requiredSkills: ['Java', 'Data Structures', 'SQL', 'Git'],
            description: 'Start your career as a software engineer working on enterprise digital transformation projects.',
        },
        {
            title: 'Platform Engineer',
            company: companies[7], location: 'Gurugram, Haryana',
            type: 'Hybrid', category: 'Software Engineering',
            salary: '₹18,00,000 - ₹28,00,000 / Year',
            minSalary: 1800000, maxSalary: 2800000,
            experienceLevel: 'Senior Level',
            tags: ['Go', 'Kubernetes', 'Docker', 'Linux'],
            requiredSkills: ['Golang', 'Kubernetes', 'Docker', 'Linux', 'Prometheus'],
            description: 'Build and scale the platform infrastructure serving 10M+ daily orders.',
        },
        // ── DevOps (4 jobs) ──
        {
            title: 'Senior DevOps Engineer',
            company: companies[0], location: 'Mumbai, Maharashtra',
            type: 'Full Time', category: 'DevOps',
            salary: '₹18,00,000 - ₹26,00,000 / Year',
            minSalary: 1800000, maxSalary: 2600000,
            experienceLevel: 'Senior Level',
            tags: ['Jenkins', 'AWS', 'Kubernetes', 'Ansible'],
            requiredSkills: ['Jenkins', 'AWS', 'Kubernetes', 'Docker', 'Ansible'],
            description: 'Lead DevOps practices and CI/CD automation across TCS delivery centers globally.',
        },
        {
            title: 'Cloud Infrastructure Engineer',
            company: companies[2], location: 'Bengaluru, Karnataka',
            type: 'Full Time', category: 'DevOps',
            salary: '₹14,00,000 - ₹20,00,000 / Year',
            minSalary: 1400000, maxSalary: 2000000,
            experienceLevel: 'Mid-Senior Level',
            tags: ['Azure', 'Terraform', 'CI/CD', 'Linux'],
            requiredSkills: ['Azure', 'Terraform', 'CI/CD', 'Linux', 'Shell Scripting'],
            description: 'Manage cloud infrastructure and automate deployments for Wipro\'s digital platforms.',
        },
        {
            title: 'Site Reliability Engineer',
            company: companies[3], location: 'Bengaluru, Karnataka',
            type: 'Full Time', category: 'DevOps',
            salary: '₹22,00,000 - ₹32,00,000 / Year',
            minSalary: 2200000, maxSalary: 3200000,
            experienceLevel: 'Expert/Principal',
            tags: ['SRE', 'Prometheus', 'Grafana', 'Kubernetes'],
            requiredSkills: ['SRE', 'Prometheus', 'Grafana', 'Kubernetes', 'On-call'],
            description: 'Ensure 99.99% uptime for Razorpay\'s payment infrastructure serving crores of transactions.',
        },
        {
            title: 'DevOps Engineer (Fresher)',
            company: companies[1], location: 'Bengaluru, Karnataka',
            type: 'Full Time', category: 'DevOps',
            salary: '₹5,00,000 - ₹8,00,000 / Year',
            minSalary: 500000, maxSalary: 800000,
            experienceLevel: 'Entry Level',
            tags: ['Linux', 'Git', 'Docker', 'Bash'],
            requiredSkills: ['Linux', 'Git', 'Docker Basics', 'Bash Scripting'],
            description: 'Join Infosys as a fresher DevOps engineer and work on automation and cloud projects.',
        },
        // ── Data Science (5 jobs) ──
        {
            title: 'Data Scientist - NLP',
            company: companies[6], location: 'Bengaluru, Karnataka',
            type: 'Full Time', category: 'Data Science',
            salary: '₹20,00,000 - ₹30,00,000 / Year',
            minSalary: 2000000, maxSalary: 3000000,
            experienceLevel: 'Senior Level',
            tags: ['NLP', 'Python', 'TensorFlow', 'BERT'],
            requiredSkills: ['NLP', 'Python', 'TensorFlow', 'PyTorch', 'BERT'],
            description: 'Build NLP models to improve product search and recommendation systems at Flipkart.',
        },
        {
            title: 'Machine Learning Engineer',
            company: companies[3], location: 'Bengaluru, Karnataka',
            type: 'Full Time', category: 'Data Science',
            salary: '₹22,00,000 - ₹35,00,000 / Year',
            minSalary: 2200000, maxSalary: 3500000,
            experienceLevel: 'Senior Level',
            tags: ['ML', 'Python', 'Scikit-learn', 'Feature Engineering'],
            requiredSkills: ['Machine Learning', 'Python', 'Scikit-learn', 'SQL', 'Feature Engineering'],
            description: 'Build ML models for fraud detection in payment transactions at Razorpay.',
        },
        {
            title: 'Business Intelligence Analyst',
            company: companies[8], location: 'Mumbai, Maharashtra',
            type: 'Full Time', category: 'Data Science',
            salary: '₹8,00,000 - ₹14,00,000 / Year',
            minSalary: 800000, maxSalary: 1400000,
            experienceLevel: 'Mid-Senior Level',
            tags: ['SQL', 'Power BI', 'Excel', 'Tableau'],
            requiredSkills: ['SQL', 'Power BI', 'Tableau', 'Excel', 'Data Analysis'],
            description: 'Analyze banking data and create dashboards for senior management at HDFC Bank.',
        },
        {
            title: 'Data Engineer',
            company: companies[7], location: 'Gurugram, Haryana',
            type: 'Full Time', category: 'Data Science',
            salary: '₹14,00,000 - ₹20,00,000 / Year',
            minSalary: 1400000, maxSalary: 2000000,
            experienceLevel: 'Mid-Senior Level',
            tags: ['Spark', 'Hadoop', 'Python', 'Kafka'],
            requiredSkills: ['Apache Spark', 'Hadoop', 'Python', 'Kafka', 'Hive'],
            description: 'Build data pipelines for analyzing 50M+ orders on the Zomato platform.',
        },
        {
            title: 'AI Research Scientist',
            company: companies[2], location: 'Bengaluru, Karnataka',
            type: 'Full Time', category: 'Data Science',
            salary: '₹25,00,000 - ₹40,00,000 / Year',
            minSalary: 2500000, maxSalary: 4000000,
            experienceLevel: 'Expert/Principal',
            tags: ['Deep Learning', 'Computer Vision', 'PyTorch', 'Research'],
            requiredSkills: ['Deep Learning', 'Computer Vision', 'PyTorch', 'Research Publication'],
            description: 'Conduct AI research projects for next-gen intelligent automation products at Wipro AI.',
        },
        // ── Design (4 jobs) ──
        {
            title: 'Senior UI/UX Designer',
            company: companies[6], location: 'Bengaluru, Karnataka',
            type: 'Full Time', category: 'Design',
            salary: '₹14,00,000 - ₹20,00,000 / Year',
            minSalary: 1400000, maxSalary: 2000000,
            experienceLevel: 'Senior Level',
            tags: ['Figma', 'UX Research', 'Prototyping', 'Design Systems'],
            requiredSkills: ['Figma', 'UX Research', 'Wireframing', 'Prototyping'],
            description: 'Lead UX design for the Flipkart seller and buyer app experiences.',
        },
        {
            title: 'Product Designer',
            company: companies[3], location: 'Bengaluru, Karnataka',
            type: 'Full Time', category: 'Design',
            salary: '₹16,00,000 - ₹24,00,000 / Year',
            minSalary: 1600000, maxSalary: 2400000,
            experienceLevel: 'Mid-Senior Level',
            tags: ['Figma', 'Adobe XD', 'User Research', 'Motion Design'],
            requiredSkills: ['Figma', 'Adobe XD', 'User Research', 'Interaction Design'],
            description: 'Design intuitive payment flows and dashboards for Razorpay\'s merchant products.',
        },
        {
            title: 'Graphic Designer',
            company: companies[4], location: 'Bengaluru, Karnataka',
            type: 'Full Time', category: 'Design',
            salary: '₹5,00,000 - ₹9,00,000 / Year',
            minSalary: 500000, maxSalary: 900000,
            experienceLevel: 'Entry Level',
            tags: ['Photoshop', 'Illustrator', 'Canva', 'Branding'],
            requiredSkills: ['Adobe Photoshop', 'Illustrator', 'Canva', 'Brand Design'],
            description: 'Create compelling educational graphics and marketing materials for BYJU\'S learning platform.',
        },
        {
            title: 'Motion Graphics Designer',
            company: companies[7], location: 'Gurugram, Haryana',
            type: 'Full Time', category: 'Design',
            salary: '₹8,00,000 - ₹14,00,000 / Year',
            minSalary: 800000, maxSalary: 1400000,
            experienceLevel: 'Mid-Senior Level',
            tags: ['After Effects', 'Premiere Pro', '2D Animation', 'Motion Design'],
            requiredSkills: ['After Effects', 'Premiere Pro', 'Motion Design', '2D Animation'],
            description: 'Produce engaging motion graphics and video content for Zomato\'s marketing campaigns.',
        },
        // ── Finance (4 jobs) ──
        {
            title: 'Chartered Accountant',
            company: companies[8], location: 'Mumbai, Maharashtra',
            type: 'Full Time', category: 'Finance',
            salary: '₹10,00,000 - ₹16,00,000 / Year',
            minSalary: 1000000, maxSalary: 1600000,
            experienceLevel: 'Mid-Senior Level',
            tags: ['CA', 'Taxation', 'Audit', 'SAP'],
            requiredSkills: ['CA Qualified', 'Tax Compliance', 'SAP FICO', 'Audit'],
            description: 'Handle statutory compliance, financial reporting and tax planning for HDFC Bank.',
        },
        {
            title: 'Financial Analyst',
            company: companies[9], location: 'Mumbai, Maharashtra',
            type: 'Full Time', category: 'Finance',
            salary: '₹8,00,000 - ₹14,00,000 / Year',
            minSalary: 800000, maxSalary: 1400000,
            experienceLevel: 'Mid-Senior Level',
            tags: ['Financial Modelling', 'Excel', 'Forecasting', 'P&L'],
            requiredSkills: ['Financial Modelling', 'Excel', 'P&L Analysis', 'Forecasting'],
            description: 'Analyze financial data and prepare detailed reports for Mahindra\'s corporate finance team.',
        },
        {
            title: 'Risk & Compliance Analyst',
            company: companies[8], location: 'Mumbai, Maharashtra',
            type: 'Full Time', category: 'Finance',
            salary: '₹12,00,000 - ₹18,00,000 / Year',
            minSalary: 1200000, maxSalary: 1800000,
            experienceLevel: 'Mid-Senior Level',
            tags: ['Risk Management', 'Compliance', 'BASEL', 'RBI Guidelines'],
            requiredSkills: ['Risk Management', 'Compliance', 'BASEL III', 'RBI Regulations'],
            description: 'Monitor and manage credit and operational risks in compliance with RBI guidelines.',
        },
        {
            title: 'Investment Banker (Fresher)',
            company: companies[8], location: 'Mumbai, Maharashtra',
            type: 'Full Time', category: 'Finance',
            salary: '₹6,00,000 - ₹10,00,000 / Year',
            minSalary: 600000, maxSalary: 1000000,
            experienceLevel: 'Entry Level',
            tags: ['Investment Banking', 'Excel', 'Valuation', 'CFA'],
            requiredSkills: ['Valuation', 'Excel', 'PowerPoint', 'Financial Analysis'],
            description: 'Start your career in investment banking with HDFC\'s corporate advisory team.',
        },
        // ── Marketing (4 jobs) ──
        {
            title: 'Digital Marketing Manager',
            company: companies[7], location: 'Gurugram, Haryana',
            type: 'Full Time', category: 'Marketing',
            salary: '₹12,00,000 - ₹18,00,000 / Year',
            minSalary: 1200000, maxSalary: 1800000,
            experienceLevel: 'Senior Level',
            tags: ['SEO', 'Google Ads', 'Social Media', 'Performance Marketing'],
            requiredSkills: ['Google Ads', 'Facebook Ads', 'SEO', 'Analytics', 'Performance Marketing'],
            description: 'Drive customer acquisition campaigns for Zomato across digital channels.',
        },
        {
            title: 'Content Marketing Specialist',
            company: companies[4], location: 'Bengaluru, Karnataka',
            type: 'Full Time', category: 'Marketing',
            salary: '₹6,00,000 - ₹10,00,000 / Year',
            minSalary: 600000, maxSalary: 1000000,
            experienceLevel: 'Entry Level',
            tags: ['Content Writing', 'SEO', 'Blog', 'Copywriting'],
            requiredSkills: ['Content Writing', 'SEO', 'Copywriting', 'WordPress'],
            description: 'Create engaging educational content for BYJU\'S digital marketing campaigns.',
        },
        {
            title: 'Brand Manager',
            company: companies[9], location: 'Mumbai, Maharashtra',
            type: 'Full Time', category: 'Marketing',
            salary: '₹14,00,000 - ₹20,00,000 / Year',
            minSalary: 1400000, maxSalary: 2000000,
            experienceLevel: 'Senior Level',
            tags: ['Brand Strategy', 'ATL/BTL', 'Market Research', 'Product Launch'],
            requiredSkills: ['Brand Management', 'ATL/BTL Marketing', 'Market Research', 'Product Launch'],
            description: 'Lead brand strategy and new product launches for the Mahindra automotive portfolio.',
        },
        {
            title: 'Growth Marketing Analyst',
            company: companies[3], location: 'Bengaluru, Karnataka',
            type: 'Hybrid', category: 'Marketing',
            salary: '₹8,00,000 - ₹13,00,000 / Year',
            minSalary: 800000, maxSalary: 1300000,
            experienceLevel: 'Mid-Senior Level',
            tags: ['Growth Hacking', 'A/B Testing', 'Analytics', 'Funnel Optimization'],
            requiredSkills: ['Growth Hacking', 'A/B Testing', 'SQL', 'Google Analytics'],
            description: 'Drive merchant onboarding and activation growth through data-driven campaigns.',
        },
        // ── Sales (3 jobs) ──
        {
            title: 'Enterprise Sales Manager',
            company: companies[0], location: 'Mumbai, Maharashtra',
            type: 'Full Time', category: 'Sales',
            salary: '₹15,00,000 - ₹22,00,000 / Year',
            minSalary: 1500000, maxSalary: 2200000,
            experienceLevel: 'Senior Level',
            tags: ['B2B Sales', 'Enterprise', 'CRM', 'Revenue Target'],
            requiredSkills: ['B2B Sales', 'Enterprise Solutions', 'CRM', 'Negotiation'],
            description: 'Drive IT services sales to large enterprises and government clients at TCS.',
        },
        {
            title: 'Inside Sales Executive',
            company: companies[4], location: 'Bengaluru, Karnataka',
            type: 'Full Time', category: 'Sales',
            salary: '₹4,00,000 - ₹7,00,000 / Year',
            minSalary: 400000, maxSalary: 700000,
            experienceLevel: 'Entry Level',
            tags: ['Inside Sales', 'Cold Calling', 'Lead Generation', 'CRM'],
            requiredSkills: ['Communication', 'Cold Calling', 'Lead Generation', 'CRM Tools'],
            description: 'Connect with students and parents to drive course enrollments for BYJU\'S.',
        },
        {
            title: 'Sales Development Representative',
            company: companies[3], location: 'Bengaluru, Karnataka',
            type: 'Full Time', category: 'Sales',
            salary: '₹6,00,000 - ₹10,00,000 / Year',
            minSalary: 600000, maxSalary: 1000000,
            experienceLevel: 'Entry Level',
            tags: ['SaaS Sales', 'B2B', 'Outbound', 'Prospecting'],
            requiredSkills: ['SaaS Sales', 'Prospecting', 'B2B Communication', 'CRM'],
            description: 'Drive new merchant acquisition for Razorpay\'s payment gateway products.',
        },
        // ── HR (3 jobs) ──
        {
            title: 'HR Business Partner',
            company: companies[1], location: 'Bengaluru, Karnataka',
            type: 'Full Time', category: 'HR',
            salary: '₹12,00,000 - ₹18,00,000 / Year',
            minSalary: 1200000, maxSalary: 1800000,
            experienceLevel: 'Senior Level',
            tags: ['HR Strategy', 'ER', 'Talent Management', 'HRBP'],
            requiredSkills: ['HR Strategy', 'Employee Relations', 'Talent Management', 'HRIS'],
            description: 'Partner with business leaders to drive people strategies across Infosys delivery units.',
        },
        {
            title: 'Talent Acquisition Specialist',
            company: companies[2], location: 'Bengaluru, Karnataka',
            type: 'Full Time', category: 'HR',
            salary: '₹6,00,000 - ₹10,00,000 / Year',
            minSalary: 600000, maxSalary: 1000000,
            experienceLevel: 'Mid-Senior Level',
            tags: ['Recruitment', 'Sourcing', 'ATS', 'Headhunting'],
            requiredSkills: ['Recruitment', 'Boolean Sourcing', 'ATS', 'Interview Coordination'],
            description: 'Lead technical hiring for cloud and AI roles across Wipro\'s digital business units.',
        },
        {
            title: 'HR Executive (Fresher)',
            company: companies[9], location: 'Mumbai, Maharashtra',
            type: 'Full Time', category: 'HR',
            salary: '₹3,00,000 - ₹5,00,000 / Year',
            minSalary: 300000, maxSalary: 500000,
            experienceLevel: 'Entry Level',
            tags: ['Recruitment', 'Onboarding', 'Payroll', 'HR Operations'],
            requiredSkills: ['Communication', 'MS Office', 'Recruitment Basics', 'Onboarding'],
            description: 'Support HR operations, recruitment drives and onboarding for Mahindra\'s corporate team.',
        },
        // ── Engineering (4 jobs) ──
        {
            title: 'Civil Engineer - Infrastructure',
            company: companies[9], location: 'Pune, Maharashtra',
            type: 'Full Time', category: 'Engineering',
            salary: '₹6,00,000 - ₹10,00,000 / Year',
            minSalary: 600000, maxSalary: 1000000,
            experienceLevel: 'Entry Level',
            tags: ['Civil Engineering', 'AutoCAD', 'Project Management', 'Structural'],
            requiredSkills: ['AutoCAD', 'Structural Analysis', 'Project Management'],
            description: 'Work on infrastructure and construction projects for Mahindra\'s manufacturing facilities.',
        },
        {
            title: 'Mechanical Design Engineer',
            company: companies[9], location: 'Mumbai, Maharashtra',
            type: 'Full Time', category: 'Engineering',
            salary: '₹7,00,000 - ₹12,00,000 / Year',
            minSalary: 700000, maxSalary: 1200000,
            experienceLevel: 'Mid-Senior Level',
            tags: ['SolidWorks', 'CAD', 'Product Design', 'Manufacturing'],
            requiredSkills: ['SolidWorks', 'AutoCAD', 'Product Design', 'GD&T'],
            description: 'Design and develop automotive components for Mahindra\'s SUV product line.',
        },
        {
            title: 'Electrical Engineer',
            company: companies[9], location: 'Pune, Maharashtra',
            type: 'Full Time', category: 'Engineering',
            salary: '₹6,00,000 - ₹10,00,000 / Year',
            minSalary: 600000, maxSalary: 1000000,
            experienceLevel: 'Entry Level',
            tags: ['Electrical Design', 'PCB', 'MATLAB', 'Embedded'],
            requiredSkills: ['Electrical Design', 'PCB Layout', 'MATLAB', 'PLC Programming'],
            description: 'Work on EV powertrain electrical design and testing for Mahindra\'s electric vehicle lineup.',
        },
        {
            title: 'Quality Assurance Engineer',
            company: companies[0], location: 'Chennai, Tamil Nadu',
            type: 'Full Time', category: 'Engineering',
            salary: '₹5,00,000 - ₹9,00,000 / Year',
            minSalary: 500000, maxSalary: 900000,
            experienceLevel: 'Entry Level',
            tags: ['QA', 'Testing', 'Selenium', 'JIRA'],
            requiredSkills: ['Manual Testing', 'Selenium', 'JIRA', 'Test Cases'],
            description: 'Ensure software quality through manual and automated testing for TCS client projects.',
        },
        // ── Healthcare (3 jobs) ──
        {
            title: 'Healthcare IT Consultant',
            company: companies[5], location: 'Chennai, Tamil Nadu',
            type: 'Full Time', category: 'Healthcare',
            salary: '₹10,00,000 - ₹16,00,000 / Year',
            minSalary: 1000000, maxSalary: 1600000,
            experienceLevel: 'Mid-Senior Level',
            tags: ['Healthcare IT', 'EMR', 'HL7', 'FHIR'],
            requiredSkills: ['Healthcare IT', 'EMR Systems', 'HL7', 'FHIR Standards'],
            description: 'Implement and manage digital health systems across Apollo Hospitals locations.',
        },
        {
            title: 'Clinical Data Analyst',
            company: companies[5], location: 'Hyderabad, Telangana',
            type: 'Full Time', category: 'Healthcare',
            salary: '₹6,00,000 - ₹10,00,000 / Year',
            minSalary: 600000, maxSalary: 1000000,
            experienceLevel: 'Mid-Senior Level',
            tags: ['Clinical Data', 'SAS', 'SPSS', 'Medical Coding'],
            requiredSkills: ['Clinical Data Analysis', 'SAS', 'SPSS', 'Medical Coding'],
            description: 'Analyze patient outcomes data to improve clinical quality metrics at Apollo Hospitals.',
        },
        {
            title: 'Hospital Administrator',
            company: companies[5], location: 'Delhi, NCR',
            type: 'Full Time', category: 'Healthcare',
            salary: '₹8,00,000 - ₹13,00,000 / Year',
            minSalary: 800000, maxSalary: 1300000,
            experienceLevel: 'Mid-Senior Level',
            tags: ['Hospital Admin', 'Operations', 'Patient Management', 'Compliance'],
            requiredSkills: ['Hospital Administration', 'Operations Management', 'Quality Compliance'],
            description: 'Oversee daily operations and administration of Apollo\'s multi-specialty hospital.',
        },
        // ── Education (3 jobs) ──
        {
            title: 'Senior Curriculum Developer',
            company: companies[4], location: 'Bengaluru, Karnataka',
            type: 'Full Time', category: 'Education',
            salary: '₹8,00,000 - ₹14,00,000 / Year',
            minSalary: 800000, maxSalary: 1400000,
            experienceLevel: 'Senior Level',
            tags: ['Curriculum Design', 'Instructional Design', 'LMS', 'Education'],
            requiredSkills: ['Curriculum Design', 'Instructional Design', 'LMS Platforms', 'Assessment'],
            description: 'Design transformative K-12 Math curriculum for BYJU\'S learning platform.',
        },
        {
            title: 'Academic Counselor',
            company: companies[4], location: 'Mumbai, Maharashtra',
            type: 'Full Time', category: 'Education',
            salary: '₹4,00,000 - ₹7,00,000 / Year',
            minSalary: 400000, maxSalary: 700000,
            experienceLevel: 'Entry Level',
            tags: ['Academic Counseling', 'Student Guidance', 'Communication'],
            requiredSkills: ['Communication', 'Counseling', 'Student Engagement'],
            description: 'Guide students and parents on the best learning paths through BYJU\'S programs.',
        },
        {
            title: 'Online Tutor - JEE/NEET',
            company: companies[4], location: 'Remote',
            type: 'Remote', category: 'Education',
            salary: '₹5,00,000 - ₹9,00,000 / Year',
            minSalary: 500000, maxSalary: 900000,
            experienceLevel: 'Entry Level',
            tags: ['Teaching', 'JEE', 'NEET', 'Online Education'],
            requiredSkills: ['JEE/NEET Subject Expertise', 'Online Teaching', 'Doubt Solving'],
            description: 'Teach JEE/NEET students online with interactive live sessions on BYJU\'S platform.',
        },
        // ── Operations (3 jobs) ──
        {
            title: 'Operations Manager - Logistics',
            company: companies[6], location: 'Bengaluru, Karnataka',
            type: 'Full Time', category: 'Operations',
            salary: '₹12,00,000 - ₹18,00,000 / Year',
            minSalary: 1200000, maxSalary: 1800000,
            experienceLevel: 'Senior Level',
            tags: ['Logistics', 'Supply Chain', 'Warehouse', 'Operations'],
            requiredSkills: ['Supply Chain', 'Warehouse Management', 'Vendor Management', 'SAP'],
            description: 'Manage end-to-end logistics and supply chain operations for Flipkart\'s fulfillment centers.',
        },
        {
            title: 'Supply Chain Analyst',
            company: companies[9], location: 'Pune, Maharashtra',
            type: 'Full Time', category: 'Operations',
            salary: '₹7,00,000 - ₹11,00,000 / Year',
            minSalary: 700000, maxSalary: 1100000,
            experienceLevel: 'Mid-Senior Level',
            tags: ['Supply Chain', 'Procurement', 'ERP', 'Demand Planning'],
            requiredSkills: ['Supply Chain', 'Demand Planning', 'SAP ERP', 'Procurement'],
            description: 'Optimize supply chain and procurement processes for Mahindra\'s automotive division.',
        },
        {
            title: 'Delivery Operations Executive',
            company: companies[7], location: 'Hyderabad, Telangana',
            type: 'Full Time', category: 'Operations',
            salary: '₹3,50,000 - ₹6,00,000 / Year',
            minSalary: 350000, maxSalary: 600000,
            experienceLevel: 'Entry Level',
            tags: ['Delivery', 'Operations', 'Fleet Management', 'Last Mile'],
            requiredSkills: ['Operations', 'Fleet Management', 'Last Mile Delivery', 'Excel'],
            description: 'Manage delivery partner operations and ensure timely food delivery for Zomato.',
        },
        // ── Non-IT (3 jobs) ──
        {
            title: 'Management Trainee',
            company: companies[9], location: 'Mumbai, Maharashtra',
            type: 'Full Time', category: 'Non-IT',
            salary: '₹7,00,000 - ₹10,00,000 / Year',
            minSalary: 700000, maxSalary: 1000000,
            experienceLevel: 'Entry Level',
            tags: ['Management', 'Leadership', 'MBA', 'Cross-functional'],
            requiredSkills: ['Leadership', 'Analytical Thinking', 'Communication', 'MBA Preferred'],
            description: 'Join Mahindra\'s prestigious management trainee program with cross-functional rotation.',
        },
        {
            title: 'Customer Success Manager',
            company: companies[3], location: 'Bengaluru, Karnataka',
            type: 'Full Time', category: 'Customer Success',
            salary: '₹10,00,000 - ₹16,00,000 / Year',
            minSalary: 1000000, maxSalary: 1600000,
            experienceLevel: 'Mid-Senior Level',
            tags: ['Customer Success', 'Onboarding', 'Churn Reduction', 'SaaS'],
            requiredSkills: ['Customer Success', 'Relationship Management', 'SaaS', 'CRM'],
            description: 'Own the success of key merchant accounts and drive retention at Razorpay.',
        },
        {
            title: 'Public Relations Manager',
            company: companies[8], location: 'Mumbai, Maharashtra',
            type: 'Full Time', category: 'Non-IT',
            salary: '₹10,00,000 - ₹16,00,000 / Year',
            minSalary: 1000000, maxSalary: 1600000,
            experienceLevel: 'Mid-Senior Level',
            tags: ['PR', 'Media Relations', 'Corporate Communications', 'Crisis Management'],
            requiredSkills: ['PR', 'Media Relations', 'Press Releases', 'Crisis Communication'],
            description: 'Lead public relations and corporate communications strategy for HDFC Bank.',
        },
    ];

    let created = 0;
    for (const jobData of jobsData) {
        const existing = await Job.findOne({ title: jobData.title, company: jobData.company._id });
        if (!existing) {
            await Job.create({
                ...jobData,
                company: jobData.company._id,
                companyName: jobData.company.name,
                postedBy: recruiter._id,
                status: 'active',
                views: Math.floor(Math.random() * 500) + 50,
            });
            created++;
            console.log(`✅ Created job: ${jobData.title} @ ${jobData.company.name}`);
        } else {
            console.log(`ℹ️  Job exists: ${jobData.title}`);
        }
    }

    console.log(`\n🎉 Seeding Complete!`);
    console.log(`   Companies: ${companies.length}`);
    console.log(`   Jobs created: ${created}`);
    console.log(`   Total jobs: ${jobsData.length}`);
    await mongoose.disconnect();
}

seed().catch(err => {
    console.error('❌ Seed error:', err.message);
    mongoose.disconnect();
    process.exit(1);
});
